name: Lighthouse

on: deployment_status

concurrency:
  cancel-in-progress: true
  group: lighthouse-${{ github.event.deployment_status.deployment_id }}

jobs:
  lhci:
    name: Run lhci on deployed environment
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: test
        run: |
          echo "deployment_status: ${{ github.event.deployment_status }}"
          echo "deployment_status.deployment_id: ${{ github.event.deployment_status.deployment_id }}"
          echo "workflow: ${{ github.workflow }}"
          echo "event_name: ${{ github.event_name }}"
          echo "event.ref: ${{ github.event.ref }}"

      - name: run lhci
        run: npx --yes @lhci/cli@latest autorun --collect.url=${{ github.event.deployment_status.target_url }}
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
