name: Lighthouse

on: deployment_status

jobs:
  lhci:
    name: Run lhci on deployed environment
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-18.04
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: run lhci
        run: npx lhci autorun --collect.url=${{ github.event.deployment_status.target_url }}
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
