name: Quality

on:
  push:
    branches: [master, alpha, beta, next]
  pull_request:

concurrency:
  cancel-in-progress: true
  group: tests-${{ github.ref }}

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      # - name: Setup Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 14

      - name: Yarn cache setup
        uses: c-hive/gha-yarn-cache@v2

      - name: Install dependencies
        run: yarn --frozen-lockfile --perfer-offline

      - name: Lint code
        run: yarn lint

  types:
    name: Types check
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      # - name: Setup Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 14

      - name: Yarn cache setup
        uses: c-hive/gha-yarn-cache@v2

      - name: Install dependencies
        run: yarn --frozen-lockfile --perfer-offline

      - name: Check types
        run: yarn type-check

  tests:
    name: Tests
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      # - name: Setup Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 14

      - name: Yarn cache setup
        uses: c-hive/gha-yarn-cache@v2

      - name: Install dependencies
        run: yarn --frozen-lockfile --perfer-offline

      - name: Run tests
        run: yarn test

      - name: Check
        run: |
          ls -lah
          ls -lah ./coverage

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage

  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-18.04
    needs: [lint, types, tests]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Download coverage
        uses: actions/download-artifact@v3
        with:
          name: coverage
          path: ./coverage/

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
