name: Quality

on:
  push:
    branches: [master, alpha, beta, next]
  pull_request:

concurrency:
  cancel-in-progress: true
  group: tests-${{ github.ref }}

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: yarn --frozen-lockfile --perfer-offline

      - name: Lint code
        run: yarn lint

  types:
    name: Types check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: yarn --frozen-lockfile --perfer-offline

      - name: Check types
        run: yarn type-check

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: yarn --frozen-lockfile --perfer-offline

      - name: Run tests
        run: yarn test

      - name: Check
        run: |
          ls -lah
          ls -lah ./coverage

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage

  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Download coverage
        uses: actions/download-artifact@v4
        with:
          name: coverage
          path: ./coverage/

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
