name: Update deaths datasets

on:
  schedule:
    - cron: "42 23 * * *"
  workflow_dispatch:

jobs:
  udpate:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: master
          token: ${{ secrets.PAT }}

      - name: Yarn cache setup
        uses: c-hive/gha-yarn-cache@v2

      - name: Install
        run: yarn --frozen-lockfile --perfer-offline

      - name: Download files
        run: ./scripts/fetch.js

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(data): Update deaths datasets."
