name: Update deaths datasets

on:
  schedule:
    - cron: "42 23 * * *"
  workflow_dispatch:

jobs:
  udpate:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
          token: ${{ secrets.PAT }}

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - name: Install
        run: yarn --frozen-lockfile --perfer-offline

      - name: Download files
        run: ./scripts/fetch.js

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(data): Update deaths datasets."
